[package]
name = "leet"
version = "0.1.0"
rust-version = "1.58.1"

[dependencies]
cargo-leet = { path = "../cargo-leet", default-features=false, featuers=["leet_env"]}

[dev-dependencies]
rstest = "0.12.0"
